### ISSUE TITLE
请求添加rtsp rtmp视频源

### ISSUE THREAD

**Issue by hasspi88** [icctvcloud/nextguard#1]
请求添加rtsp rtmp视频源

**Comment by ninerap** [comment]
如果你的rtsp视频源是一网络摄像机 ，可以试试我们的onvif功能，用户名/密码就是你rtsp流的用户名/密码。
rtmp，我们后续增加一下。
觉得我们的项目不错，请给我们打星，让更多的人看到。

**Comment by hasspi88** [comment]
添加上不上线，其他录像机都正常搜到，能直接添加rtsp地址吗

**Comment by ninerap** [comment]
你加不上的设备不支持ONVIF，是吗？是什么品牌的设备？rtsp要加也没有这么快的。

**Comment by ninerap** [comment]
@hasspi88  版本v1.6发布了，新增了rtsp设备的接入。你可以试试。

**Comment by hasspi88** [comment]
感谢通知



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ninerap ***@***.***&gt;
发送时间: 2024年7月30日 12:06
收件人: 24021438 ***@***.***&gt;
主题: Re: [icctvcloud/nextguard] 请求添加rtsp rtmp视频源 (Issue #1)





 
版本v1.6发布了，新增了rtsp设备的接入。你可以试试。
