### ISSUE TITLE
Error pull image icctvcloud/nextguard:v1.5 

### ISSUE THREAD

**Issue by thoai112** [icctvcloud/nextguard#2]
I can't  pull image pull image icctvcloud/nextguard:v1.5  and Error response from daemon: Get "https://registry.cn-hangzhou.aliyuncs.com/v2/": net/http: TLS handshake timeout.

![Screenshot 2024-07-27 231615](https://github.com/user-attachments/assets/f3c4a490-1cb0-4f01-b5f7-9bde7834ff73)

**Comment by silverfox07** [comment]
Can you tell me what region you are in？I'll test the CDN connection.

**Comment by thoai112** [comment]
> Can you tell me what region you are in？I'll test the CDN connection.

Region in VietNam. I tried in Singapore but it didn't work.

**Comment by ninerap** [comment]
@thoai112, V1.6 is released，we add docker image multiple sources.You can try it.
